services:
  - type: web
    name: lana-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    publishDir: ./
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ieqqsgpaivxmcgcflanu.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcXFzZ3BhaXZ4bWNnY2ZsYW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODI5ODAsImV4cCI6MjA3Mzk1ODk4MH0.H0XLpSpgQ7Fypy7iOFu4aY7zsQ47eDkaeh6Y5ci0HQc
      - key: NEXT_PUBLIC_API_BASE
        value: https://lana-ai.onrender.com