services:
  - type: web
    name: lana-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start -p $PORT
    publishDir: ./.next
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_API_BASE
        sync: false